# https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/environment-variables-full-list-github-actions
---
name: CI - Ruby

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]

jobs:
  build:
    steps:
      - name: Show env vars
        run: env

  unit-tests:
    name: Unit Tests
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: 3.0.6
            os: ubuntu
          - ruby-version: 3.0.6
            os: windows
