# https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/environment-variables-full-list-github-actions
---
name: CI - Ruby

on: #  yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    # uses: ./.github/workflows/bazel.yml
    with:
      name: Build
      run: env

  unit-tests:
    name: Unit Tests
    needs: build
    # uses: ./.github/workflows/bazel.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: 3.0.6
            os: ubuntu
          - ruby-version: 3.0.6
            os: windows
