---
name: Ruby

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']

    steps:
      - uses: actions/checkout@v3
      - name: Install and setup tor
        run:
          - sudo apt-get install -y tor
          - tor --version
          - sh -c 'echo SOCKSPort 9050 > /etc/tor/torrc'
          - sh -c 'echo ControlPort 9051 >> /etc/tor/torrc'
          - export HashedControlPassword=$(tor --quiet --hash-password "")
          - sh -c 'echo "HashedControlPassword $HashedControlPassword" >> /etc/tor/torrc'
          - sh -c 'cat /etc/tor/torrc'  # show torrc
          # https://askubuntu.com/questions/365911/why-the-services-do-not-start-at-installation
          - service tor start  # cos it's docker
          - pidof tor

      - name: Set up Ruby
        # Automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Check tor running
        run: curl -x socks5h://127.0.0.1:9050 http://ipecho.net/plain
