---
name: Ruby

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1']

    steps:
      - uses: actions/checkout@v3
      # - name: Install python stuff
      #   run: |
      #     sudo apt install python3-dev python3-pip
      #     pip3 install pip numpy wheel packaging requests opt_einsum
      #     pip3 install keras_preprocessing --no-deps

      # - name: Install tensorflow
      #   run: |
      #     wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.8.0.tar.gz
      #     tar -xf libtensorflow-gpu-linux-x86_64-2.8.0.tar.gz
      #     ./configure

      - name: Install model
        run: |
          wget https://storage.googleapis.com/download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz
          tar xf ssd_mobilenet_v1_coco_2018_01_28.tar.gz
      - name: Set up Ruby  # not needed here
        # Automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Check model
        run: ls
